### ISSUE TITLE
Colors not showing up

### ISSUE THREAD

**Issue by httpNick** [lysyi3m/osx-terminal-themes#1]
Hello,

When I install a theme such as AdventureTime it doesn't show up in the terminal properly. I think I am missing some kind of intermediate step? Here is a screenshot of what it shows after installing AdventureTime on my machine. I tried installing Tomorrow night and the text was just grey. Anyone know what I am missing? Thanks, and thank you for all the themes!

![screen shot 2015-10-15 at 11 32 51 pm](https://cloud.githubusercontent.com/assets/7322529/10535163/3683badc-7395-11e5-98b2-4ab47b708b59.png)

**Comment by lysyi3m** [comment]
Hi!

Thank you for your feedback! It looks like you've don't enabled "Display ANSI colors" option in Terminal's preferences (⌘+, and go to "Profiles" tab).

Hope it helps.

**Comment by httpNick** [comment]
Hey there thanks for the reply. - I believe I have it enabled. Is there anything that looks wrong here?

![screen shot 2015-10-15 at 11 49 36 pm](https://cloud.githubusercontent.com/assets/7322529/10535398/8133fd60-7397-11e5-86b2-4caa829532a7.png)

**Comment by lysyi3m** [comment]
Okay, I see. Color schemes itself are just overwrite ANSI-color values in Terminal.app, but you have to enable color formatting in command line utilities to see any formatted output. 

Here some options:
1. Manually enabling colro formatting for such commands like `ls`:
Open your .bash_profile or .bash_profile (I  believe you're using bash shell, am i right?) in any text editor like `nano ~/.bash_profile` and paste following somewhere in the end of file: 
```
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
```
Then save it, exit editor and type `source ~/.bash_profile`.

2. Simpler variant: install [grc](https://github.com/garabik/grc) via [homebrew](http://brew.sh/) 
```
brew install grc
echo ‘source “`brew –prefix grc`/etc/grc.bashrc”‘ >> ~/.bash_profile
source ~/.bash_profile
```
It'll give you more color formatting options 

3. Another great solution - install zsh shell [with oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). There are dozen of formatting themes for shell prompt (with coloring output). It works pretty well with schemes in my repo.

**Comment by gantaa** [comment]
Thanks for the bash_profile tip.  works great!

**Comment by lysyi3m** [comment]
@gantaa, cheers! 🍻

**Comment by darongE** [comment]
This command didn't work. type this.
echo 'source "`brew --prefix grc`/etc/grc.bashrc"' >> ~/.bash_profile

**Comment by darongE** [comment]
I fix my bug.. Thanks all !
<img width="586" alt="2016-10-15 1 44 07" src="https://cloud.githubusercontent.com/assets/3068049/19407460/c014ecae-92dd-11e6-92c7-736afb94f156.png">

**Comment by npoisonivy** [comment]
I got this error "Error: Unknown command: –prefix" after running below line..
echo ‘source “`brew –prefix grc`/etc/grc.bashrc”‘ >> ~/.bash_profile

Can anyone please help me on this? This is what I have at my file:
![image](https://user-images.githubusercontent.com/13814618/40201562-402c6002-59d4-11e8-9afe-b51389e28322.png)

The file name displayed on my Finder is 
![image](https://user-images.githubusercontent.com/13814618/40201580-4bb1af18-59d4-11e8-9624-07ad0ce29a1d.png)

But somehow on my sublime, the file name is corrupted as this. I am not sure if this cause the problem.
![image](https://user-images.githubusercontent.com/13814618/40201629-69056230-59d4-11e8-9646-86bbbfbb2c91.png)

**Comment by lysyi3m** [comment]
@nasht00 oops. Some weird formatting issue. Snippet updated.

**Comment by cemuka** [comment]
I couldn't make it work either. `echo` line return that error: `-bash: $: command not found`.

**Comment by lysyi3m** [comment]
@cemuka `$` sign represents the standard shell prompt and is usually used to show that the commands need to be entered in terminal. `$` **is not part of the command**

**Comment by cemuka** [comment]
@lysyi3m oh my bad! didn't notice it. thank you!

**Comment by ng-xcv** [comment]
Thanks a lot ☺️

**Comment by smartin** [comment]
Thank u!

**Comment by dat-le-4** [comment]
I got the error no such file or directory: /opt/homebrew/etc/grc.bashrc when run source ~/.bash_profile

**Comment by vwtlin** [comment]
Thanks a lot for the solution!

**Comment by gsmondras** [comment]
> Okay, I see. Color schemes itself are just overwrite ANSI-color values in Terminal.app, but you have to enable color formatting in command line utilities to see any formatted output.
> 
> Here some options:
> 
> 1. Manually enabling color formatting for such commands like `ls`:
>    Open your .bash_profile or .bash_profile (I  believe you're using bash shell, am i right?) in any text editor like `nano ~/.bash_profile` and paste following somewhere in the end of file:
> 
> ```
> export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
> export CLICOLOR=1
> export LSCOLORS=ExFxBxDxCxegedabagacad
> alias ls='ls -GFh'
> ```
> 
> Then save it, exit editor and type `source ~/.bash_profile`.
> 
> 2. Simpler variant: install [grc](https://github.com/garabik/grc) via [homebrew](http://brew.sh/)
> 
> ```
> $ brew install grc
> $ echo 'source "`brew --prefix`/etc/grc.bashrc"' >> ~/.bash_profile
> $ source ~/.bash_profile
> ```
> 
> It'll give you more color formatting options
> 
> 3. Another great solution - install zsh shell [with oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). There are dozen of formatting themes for shell prompt (with colorized output). It works pretty well with schemes in my repo.



This looked promising (same thing seems to be happening to me?), but i am using zsh already. Should I manually enable color formatting in my .zshrc?
