### ISSUE TITLE
PencilLight has seemingly incorrect background color compared to screenshot

### ISSUE THREAD

**Issue by dill0wn** [lysyi3m/osx-terminal-themes#10]
![ScreenGrab](https://cloud.githubusercontent.com/assets/1267330/16393162/9af92c66-3c7d-11e6-98d6-884ce13a3e92.png)

According to this, these are two very different colors.  Now... I realize this might be a limitation of the different color spaces used by web vs by MacOS, but this seems like a VERY big difference (at least to my eyes).

**Comment by lysyi3m** [comment]
@dill0wn yeah looks so 😞  
I've updated previews for that. Anyway, thank you.

**Comment by zhulduz** [comment]
@lysyi3m, I have just noticed that not only `Pencil Light` has a different screenshot.
`Wombat`, `Wryan`, `Zenburn`, etc have the same incorrect screenshots.

Could you please check them out? )

**Comment by lysyi3m** [comment]
Hey, @zhulduz! Yeah, it seems like some screenshots don't correspond actual schemes 😞. I've created a separate issue for that - #21
