### ISSUE TITLE
generate human readable colors table out of .terminal file

### ISSUE THREAD

**Issue by dant3** [lysyi3m/osx-terminal-themes#15]
Is there a way to parse .terminal file to get rgb color values out of it? I can hack it myself if you can give me a hint on how to parse it.
I would like to have a list of colors used in a terminal theme.
Preferably I want it done in cross-platform way to simplify themes export into iTerm/linux terminal apps or preview of colors used in a theme for example in a web app.

**Comment by lysyi3m** [comment]
You can use this tool https://github.com/seenaburns/osx-terminal-themer to generate json from your `.terminal` files. It's written in python about 3 years ago, but still working, I guess.

**Comment by dant3** [comment]
Indeed it works, thanks!
Unfortunately however it fails with .terminal file exported from Terminal.app with xml parsing error.

```
xml.parsers.expat.ExpatError: not well-formed (invalid token):
```

But I guess I can live with it.
