### ISSUE TITLE
file is corrupt

### ISSUE THREAD

**Issue by potatoker** [lysyi3m/osx-terminal-themes#28]
Hi,

I double clicked the .terminal file and it goes:

<img width="413" alt="screen shot 2017-08-16 at 11 39 20 pm" src="https://user-images.githubusercontent.com/5286501/29371875-2968ecca-82dc-11e7-89ff-4ae6d12b1943.png">

why is it corrupt?

**Comment by lysyi3m** [comment]
Hey @potatoker! I have no idea why this happens. Just checked all the files (twice, actually) - everything looks ok. 

In which way do you download the themes? Via "Open as Raw" -> "save as.." menu or via "clone or download" menu?

**Comment by lysyi3m** [comment]
Let's close this for now, since there is no new reports about this issue.

**Comment by mikebronner** [comment]
I'm actually getting this error now as well with a completely fresh install of macOS High Sierra 10.13.3.

**Comment by G00fY2** [comment]
1+

**Comment by stoberov** [comment]
I was having the same issue. 

Resolved by downloading/cloning the whole repo, **instead of** downloading via browser just the one .terminal file I wanted. Not sure why, but ... it works now :)
