### ISSUE TITLE
Tmux key bindings for OSX terminal 

### ISSUE THREAD

**Issue by bryanhuntesl** [lysyi3m/osx-terminal-themes#29]
This stuff works in Iterm 2 but I've really lost trust after some recent security issues (actually I evaluated it a number of years ago and didn't trust it then, but that's another matter).

Anyhow, with OSX terminal you have to do some tricks to send the ctrl-b-(arrow) keys to tmux.

The work around is described on [superuser.com](https://superuser.com/questions/660013/resizing-pane-is-not-working-for-tmux-on-mac/660072#660072), I've been doing this for years now.  

Would be great if osx-terminal-themes could ship with this pre-configured, dumb apple configuration file format is kinda opaque though, not sure how to edit all the terminal files automatically.

**Comment by lysyi3m** [comment]
Hi @bryanhuntesl ! 

Thanks for your response, but as its name suggests, this repository contains only _themes_ and not configs. So I have no plans to provide any kind of configs, settings or "hacks" for  3rd party software here. 

People, installing themes, expect that they will receive only themes without additional stuff.
