### ISSUE TITLE
Could you add the script used to generate preview images of each theme?

### ISSUE THREAD

**Issue by kebno** [lysyi3m/osx-terminal-themes#7]
Thanks for this collection/conversion of iterm2 themes!

I'd like to be able generate preview images of my own (own code snippet, own language).

I find that I like/dislike terminal themes based a lot on how specific languages/programs look in them.

Could you add  to the repo the script you use for the preview images?

Thanks.

**Comment by lysyi3m** [comment]
Hey, @kebno! 

I've added those script for generating previews. You can find it in [`tools/preview.sh`](https://github.com/lysyi3m/osx-terminal-themes/blob/master/tools/preview.sh)

It will produce "table" like this: 
![image](https://cloud.githubusercontent.com/assets/1247371/15344163/a74bfeb0-1ca4-11e6-8857-0ba4986a60ec.png)

**Comment by kebno** [comment]
thank you!
