### ISSUE TITLE
How I change my own theme to the Solarized Dracula?

### ISSUE THREAD

**Issue by BirdandLion** [lysyi3m/osx-terminal-themes#8]
I download sox-terminal-themes-master files and double click Solarized Darcula.terminal to open a new terminal window, but it can't perform the new theme, even I import to my Preference->Description file, it still not work.

**Comment by lysyi3m** [comment]
@BirdandLion try to follow this steps https://github.com/lysyi3m/osx-terminal-themes/issues/1#issuecomment-148635036

**Comment by lysyi3m** [comment]
Since nothing happens here, let's close this issue.
